;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-semi&comma
        cycle-spacing
        forward-sentence
        indent-for-tab-command
        org-end-of-line
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        pixel-scroll-precision
        ))
